### ISSUE TITLE
Initialize Character: Not loading all meshes

### ISSUE THREAD

**Issue by JohnCWakley** [vini-guerrero/Godot_Game_Tools#30]
I followed the latest youtube video I could find and followed along using the same model from Mixamo (Skeletonzombie T Avelange). This worked as expected.

When using a model with multiple meshes from Mixamo (Knight D Pelegrini), only the "Lower_Armor" was imported. This particular model, when importing using Blender's FBX importer, has 3 meshes ("Body", "Head_Hands", "Lower_Armor").

**Comment by vini-guerrero** [comment]
Hello @JohnCWakley yeap, each model with have it's own particularities and should be treated individually. Either way, that's why GGT v2 provides a tool to join the meshes into one as you can see in this menu

![image](https://user-images.githubusercontent.com/18181786/95992925-dd46e100-0e04-11eb-8d1f-cb5dfe1c6d44.png)

For models with this type of setup, broken into various pieces. I've had more success by joining meshes and re-rigging again with a single body piece on my tests. Let us know if you find a better approach.

**Comment by JohnCWakley** [comment]
@vini-guerrero : Thank you for the reply and information. I will give this a try...

**Comment by vini-guerrero** [comment]
Fixed with v2.0.5

https://github.com/vini-guerrero/Godot_Game_Tools/releases/tag/v2.0.5
