### ISSUE TITLE
Instructions are outdated

### ISSUE THREAD

**Issue by nsrosenqvist** [vini-guerrero/Godot_Game_Tools#35]
Hey there, would love to use the plugin but I'm unable to figure out how to use it properly. All tutorials are outdated as well as official instructions.txt. Would love to see the official documentation updated! Thanks!

**Comment by vini-guerrero** [comment]
Hi @nsrosenqvist , docs and video still need to be updated. But for now you can use this video as a reference, pretty much only highest workflow difference is on import, now done thru the addon instead of Blender's import.

https://youtu.be/kwMB_486xaU

**Comment by nsrosenqvist** [comment]
Thanks! That video was very helpful!

**Comment by vini-guerrero** [comment]
I will try to record a new one when I have some free time. But the workflow remains the same.

**Comment by peardox** [comment]
I've just written an idiot guide detailing how to use GGT to combine Mixamo models not specifically targeted at any specific game engine. My primary motivation for writing this was to help out CGE (Castle Game Engine) developers but the tutorial is of use to anyone who wants to use GGT.

The tutorial assumes no prior knowledge other than the ability to install Blender and ends up with a functional export for any game engine. The tutorial is of the "click this, click that" style making it extremely hard to get wrong.

I don't use Godot so the tutorial has a very simple purpose, combine a load of models - nothing else.

It took me a day and a half to export my first proper project (although this was mostly due to Mixamo's undocumented upload character section). Happily, I've worked out how to upload a model so will be following up with a tutorial on that subject and combining it with GGT.

https://peardox.com/merging-mixamo-models-using-godot-game-tools/
